apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: samrs
spec:
  replicas: 4
  selector:
    matchLabels:
      team: aigint
  template:
    metadata:
      name: testpod1
      labels:
        team: aigint
    spec:
      containers:
        - name: cont1
          image: nginx:latest
          ports:
           - containerPort: 80   